### ISSUE TITLE
SimpleLattice will not be listed.

### ISSUE THREAD

**Issue by hansnolte** [BenjaminSauder/SimpleLattice#1]
Hi BenjaminSauder,

I was really looking forward to having SimpleLattice available for Blender 2.8.
Unfortunately, SimpleLattice is not listed under the search function (F3).
I have also renamed the folder from SimpleLattice-master to simplelattice, without success...

Strangely enough, a SimpleLattice-Object is created when I call the normal Lattice command through the search function.

Win 7 Pro
Build from Today: blender-2.80-a91886e76ebd-win64
GTX 1070

Many Greetings
Hans

**Comment by BenjaminSauder** [comment]
hey, this is all still quite early and not really tested.

The operators are called "Create Lattice" & "Apply Lattice" at the moment, this might change again tho. So youre already calling the addon.

Beware that there are some unresolved issues - Im not entirely sure but it seems that some parts of blender 2.8 are also still buggy.

**Comment by hansnolte** [comment]
Hi Benjamin,

many thanks for your answer.

That the the operator called Create Lattice confused me a bit, because you wrote [here](https://github.com/BenjaminSauder/SimpleLattice) "Basically just select objects/vertices and run>**SimpleLattice**."

But it works great and yes you are right, 2.8 is still very buggy.

Many thanks for this great little timesaver.
Hans

**Comment by BenjaminSauder** [comment]
hey there - yes the documentation is pretty bare bones or even wrong ;)

I will update this soonish, need to implement a silly workound for something and do more testing :)

**Comment by hansnolte** [comment]
_I will update this soonish..._

Great to hear, but first the Blender developers have to correct a fat bug.
In the latest build, you can't see curves anymore, only when you go into edit mode, they are visible.

With such a serious bug, I'm sure it will be fixed very soon.

![no-curves](https://user-images.githubusercontent.com/7922627/50338134-b1fa5000-0513-11e9-91bf-d49fb44da49c.gif)

**Comment by BenjaminSauder** [comment]
yup lattice drawing was broken at some point, nothing i could do about ;)

but its fixed for a few weeks now.
