### ISSUE TITLE
Error when the scene has no active object

### ISSUE THREAD

**Issue by yyc12345** [BenjaminSauder/SimpleLattice#10]
## Brief Intro
This bug is not harmful. This bug will disappear when any object added into scene.
The reason why I frequently trigger this bug, is that I use an empty Blender file as my default Blender startup file.

## How to Reproduce:

0. Create a new Blender file.
0. Remove all objects in Outline View. Keep a clean Outline View.
0. Right-clicking 3D View, or clicking Object menu in 3D View, both of them will cause this bug.

## Environment

Blender version: 3.3 (Can be reproduced on 3.3. But this bug I have experienced too much times in some old versions of Blender.)  
Traceback:  
```
Traceback (most recent call last):
  File "E:\Blender\3.3\scripts\modules\bpy_types.py", line 904, in draw_ls
    func(self, context)
  File "E:\Blender\3.3\scripts\addons_contrib\SimpleLattice\__init__.py", line 152, in context_menu
    show_create_op = op_LatticeCreate.Op_LatticeCreateOperator.poll(context)
  File "E:\Blender\3.3\scripts\addons_contrib\SimpleLattice\op_LatticeCreate.py", line 128, in poll
    if (context.active_object.type in util.allowed_object_types and
AttributeError: 'NoneType' object has no attribute 'type'
```

## Possible Solution
Add a None checker for `context.active_object` in here:
https://github.com/BenjaminSauder/SimpleLattice/blob/d119c68e7c6d574aff2c6c27188c69df0db20ca1/op_LatticeCreate.py#L128

**Comment by EugeneDudavkin** [comment]
Thanks! I will check!

**Comment by EugeneDudavkin** [comment]
Done. Good catch. Thanks again!

**Comment by yyc12345** [comment]
Thanks! Problem solved.
