### ISSUE TITLE
Simple lattice not taking into account modifier stack

### ISSUE THREAD

**Issue by dimitarsp** [BenjaminSauder/SimpleLattice#11]
Hi, in Blender 3.5, Simple Lattice is not taking into account the modifier stack when calculating the bounding box. The toggle in the addon's preferences for ignoring modifiers does not make a difference, but is left unchecked.

Here is an example of a simple object with two array modifiers, and the simple lattice is created on top of the bounding box of the geometry prior to the modifiers

![image](https://user-images.githubusercontent.com/2496411/237059303-f824c176-637f-4f70-adf3-b9797f3c169e.png)

**Comment by EugeneDudavkin** [comment]
Thanks for this catch!
I'll see what the problem is.

**Comment by EugeneDudavkin** [comment]
Made a quick fix.
Removed "On top"/"Bottom" deprecated feature.
Now it should take into account all modifiers stack.
And if need to ignore all modifiers, there is "Ignore Modifiers" feature.

**Comment by Wolfgang-IX** [comment]
I can confirm it's working properly now.
