### ISSUE TITLE
Doesn't work correctly.

### ISSUE THREAD

**Issue by hansnolte** [BenjaminSauder/SimpleLattice#2]
Hi Benjamin,

in the version Dec 22, 2018 you will need several attempts to assign the latticce to an object.
When it finally works, the object has no modifier.
You have to "set Parent to" by hand.

The old version of Dec 19, 2018 works perfectly.

Blender Build from Yesterday: dafaa6f22881

**Comment by BenjaminSauder** [comment]
Hey not sure which version you mean, just try again, pushed some changes yesterday might fixed your issues as well.

**Comment by hansnolte** [comment]
Hi Benjamin,

the Version from yesterday is buggy.

[simplelattice-works.zip](https://github.com/BenjaminSauder/SimpleLattice/files/2705910/simplelattice-works.zip)

And from Yesterday:
[SimpleLattice-does-not-work.zip](https://github.com/BenjaminSauder/SimpleLattice/files/2705911/SimpleLattice-does-not-work.zip)

**Comment by BenjaminSauder** [comment]
just dumping random zip files doenst really help.

describe simple steps to reproduce - otherwise this is just a guessing game.

**Comment by hansnolte** [comment]
- Default Cube
- Edit Mode->Select Points
- F3->Create Lattice
- Nothing happends
- Repeat Create Lattice a few times 
- At some point the Lattice Object will appear, but it is not parenting to the Cube.

**Comment by BenjaminSauder** [comment]
these steps work as intended, maybe blender changed in the meantime, and things got better?

there exists some weird update problem, not sure whats causing that.
