### ISSUE TITLE
Request: BSpline as default interpolation

### ISSUE THREAD

**Issue by MetinSeven** [BenjaminSauder/SimpleLattice#3]
Hi Benjamin,

Many thanks for this very useful tool. This should be a default tool in Blender, in my humble opinion.

May I ask for BSpline to be the default interpolation type. This would save users a number of clicks to set all axes from Linear to BSpline interpolation.

Thank you.

**Comment by BenjaminSauder** [comment]
its now possible to set a default interpolation in the addon preferences.

right now it sets this only for the first time the operator runs, such that on later usage it behaves like the rest of blender where the tools keep their last used setting.

could be made to always force the defaults as well.. not sure if i like that tho.

**Comment by MetinSeven** [comment]
Thanks Benjamin! It's fine as it is now, with the preferences, nice work.
