### ISSUE TITLE
SimpleLattice seems broken in the latest Blender 2.8 betas

### ISSUE THREAD

**Issue by MetinSeven** [BenjaminSauder/SimpleLattice#4]
Hi Benjamin,

SimpleLattice seems to not be working anymore in the latest Blender 2.8 betas. There have been multiple changes to the API. Other add-ons have issues as well.

Thanks in advance for fixing it.

Kind regards,

Metin

**Comment by BenjaminSauder** [comment]
hey thanks for note! yeah i wanted to get back to this - just need to find some free time for this.

**Comment by MetinSeven** [comment]
Cool, thanks for your reply. I really like SimpleLattice.

It'd be great if you could also set BSpline to the default method, thanks!

**Comment by BenjaminSauder** [comment]
should work again

**Comment by MetinSeven** [comment]
Thanks Benjamin, it works again indeed. 👍
