### ISSUE TITLE
Addon Almost completely useless

### ISSUE THREAD

**Issue by noc2art** [BenjaminSauder/SimpleLattice#5]
I tried using this addon for the last 2 weeks and in almost all instances it let me down. I first thought that modifiers were suspect in this, but nope. The glitchy results occur randomly. Sometimes the lattice is created with a zero scale on a random (not necessarily the active) component. Sometimes across a group of them and mostly the weight map associated with it is created with zero weights. I'm on the official release of Blender 2.8 (2.80.75)

I'm kind of surprised all this could escape your attention. I do hope you get to get it to work.

AJ

**Comment by BenjaminSauder** [comment]
hey this addon is still heavily wip and unfinished. Thus the very minimalistic / non-exsistant documentation.
