### ISSUE TITLE
adding lattice to flat geometry means it can't be edited (3.0)

### ISSUE THREAD

**Issue by RichMakeGame** [BenjaminSauder/SimpleLattice#7]
This might be a blender bug, but if you apply a lattice to a flat object eg a newly created plane, the lattice won't deform the object. seems like the lattice doesn't like a scale of 0 in one dimension, if it's changed to a very small number instead it works

**Comment by Wolfgang-IX** [comment]
i have this issue too on 2.93.4 and 3.0
for now the simple fix is adding volume first, add lattice and remove the added volume. now you can edit it with lattice.
![image](https://user-images.githubusercontent.com/47208316/150661980-9f08f819-f152-4b47-aa3b-874e73d5406d.png)

**Comment by EugeneDudavkin** [comment]
Hello,
sorry for late response.
Made a quick fix. Try it now.

**Comment by Wolfgang-IX** [comment]
Hello, I can confirm it, it's working now 😁 
thank you

**Comment by RichMakeGame** [comment]
@EugeneDudavkin thank you!
