### ISSUE TITLE
Error when applying lattice to curve, text or nurbs

### ISSUE THREAD

**Issue by RichMakeGame** [BenjaminSauder/SimpleLattice#8]
Hi, apologies for adding another bug report after you've just updated! I just started using more thanks to update and found this issue-

create any type of curve eg. Add>Curve>Path , apply simple lattice - error message pops up

I also observed similar errors on nurbs surface and text.

Thanks again for the fantastic work!

**Comment by EugeneDudavkin** [comment]
Hello,
I made a quick fix.
Have a try.

!NOTE:
for nurbs -  after apply it may difference than on screen, it's how nurbs works.
for text - not possible to apply lattice and save font object, it would be converted to mesh and applying lattice.

**Comment by RichMakeGame** [comment]
Thanks so much! it works great on curves and nurbs, I did get this error when I applied it to some text:

Python: Traceback (most recent call last):
  File "C:\Users\rich\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SimpleLattice-master\op_LatticeCreate.py", line 209, in execute
    self.coords = self.get_coords_from_objects(objects)
  File "C:\Users\rich\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SimpleLattice-master\op_LatticeCreate.py", line 314, in get_coords_from_objects
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=False, properties=False)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Font's can only have scale applied: "Text"

**Comment by EugeneDudavkin** [comment]
Found. Will investigate.

**Comment by EugeneDudavkin** [comment]
Have a try ones more.

**Comment by EugeneDudavkin** [comment]
If you download it before this message - redownload. I made a mistake before, now it should work.

**Comment by RichMakeGame** [comment]
sorry just got a chance to test - looks good to me!! thanks again great work :)
