### ISSUE TITLE
Error when trying to create lattice on a multi-user (instanced) object.

### ISSUE THREAD

**Issue by mahreeoocedev01** [BenjaminSauder/SimpleLattice#9]
First of all, thank you for your work!

I tested this on Blender 3.1.2, 3.3.2, 3.4.1 and 3.5.0(alpha), using version 0.1.5 of the addon. It happens on all of them.

The issue is easy to replicate: create a cube primitive (any mesh primitive will do). Instance it using Alt-D. From object context menu choose "Simple Lattice Create". Blender throws the following error:

Python: Traceback (most recent call last):
  File "D:\Grafica\Blender 3.4\3.4\scripts\addons_contrib\SimpleLattice\op_LatticeCreate.py", line 209, in execute
    self.coords = self.get_coords_from_objects(objects)
  File "D:\Grafica\Blender 3.4\3.4\scripts\addons_contrib\SimpleLattice\op_LatticeCreate.py", line 314, in get_coords_from_objects
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=False, properties=False)
  File "D:\Grafica\Blender 3.4\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot apply to a multi user: Object "Cube.001", Mesh "Cube.001", aborting

Before this I was using version 0.1.2 of the addon and I had no issues using it on instanced objects.

**Comment by EugeneDudavkin** [comment]
Hi,
thanks. I will roll back some changes

**Comment by EugeneDudavkin** [comment]
Rolled back. Wanted to recalculate more accurate object bbox for lattice.
Now it should work as before.

**Comment by EugeneDudavkin** [comment]
Note! that after applying lattice on instance it become a mesh

**Comment by mahreeoocedev01** [comment]
Thanks for the quick reply and fix. 

I understand the reasoning. You needed to apply the object rotation in order to have it world aligned. And when trying to do this on an object with shared data, Blender would throw an error.

One possible workaround, in order to get the behavior you want, is to temporarily duplicate the object along wit the object data, apply the transforms, create the lattice based on the new object's current bounds, then deleting the temporary object and setting the lattice back to the original object.
Unless there's something else I'm missing, this would probably work as intended.

Thanks again!

**Comment by EugeneDudavkin** [comment]
Thanks for the advice, it should help!
